# Global paths
state_db: "/home/uowadmin/iosco/data/state.db"

iosco:
  csv_root: "/home/uowadmin/iosco/data/csv"
  nca_id: ""        # e.g., "64" for NZ; leave empty for all NCAs
  subsection: "main"
  request_timeout_seconds: 60

# Scheduling
schedule:
  base_date: "2025-09-01"
  daily_run_time: "13:00"     # local time for the daily ingestion + orchestration (24h)

queue:
  max_parallel_crawl_jobs: 5
  max_parallel_download_jobs: 1
  max_retries: 3 # now applies only to wayback download jobs, retry for browsertrix crawl jobs is handled via tool.py manually
  reconcile_interval_seconds: 30 # how often the worker polls Browsertrix or wb downloader to refresh job statuses

# Liveness
liveness:
  timeout_seconds: 10
  treat_http_4xx_as_live: true
  max_parallel_probes: 30

# Browsertrix integration
browsertrix:
  base_url: "http://localhost:30870"
  username: "admin@example.com"
  password: "PASSWORD!"
  org: "My Organization"
  collection: "iosco"
  crawler_setting:
    max_time: 86400  # max crawl time in seconds
    max_size: 10737418240 # max crawl size in bytes
    # crontab format frequency: min, hour, dom, mon, dow; e.g, "0 0 * * 1" run every Monday 00:00;
    # run once if not specified
    frequency: ""
# Dead-site acquisition
wb_downloader:
  output_dir: "/scratch/iosco/wayback"
  concurrency: 3          # how many files to download in parallel for Wayback downloads

# Dashboard
web:
  enable_status_page: true
  host: "127.0.0.1"
  port: 8090
  basic_auth:
    enabled: false
    username: "admin"
    password: "admin"

logging:
  level: DEBUG                 # DEBUG | INFO | WARNING | ERROR
  file: "/home/uowadmin/iosco/crawler.log"
  rotate:
    when: "midnight"          # Timed rotation; alternatives: "S","M","H","D","W0"-"W6"
    backupCount: 14           # keep last 14 files
  console: true               # also log to stdout (useful in dev)
  json: false                 # set true if you prefer JSON logs

tool:
  liveness_check_output: "/home/uowadmin/iosco/liveness"